import { Save } from "lucide-react";
export default function Preferences() {
  return <>
    <div className="page-title-row"><div><span className="eyebrow">Configuration</span><h1>Job Preferences</h1><p>Tell JobPilot what kind of opportunities you want.</p></div><button className="primary-btn"><Save size={16}/> Save Preferences</button></div>
    <div className="form-grid">
      <section className="panel"><span className="eyebrow">Employment</span><h2>What are you looking for?</h2><div className="choice-grid">{["Full-time","Contract","Contract-to-hire","Part-time"].map(x=><label className="choice" key={x}><input type="checkbox" defaultChecked={x==="Full-time"||x==="Contract"}/><span>{x}</span></label>)}</div><div className="form-fields"><label>Job titles<input defaultValue="Golang Developer, Backend Developer, Software Engineer"/></label><label>Minimum salary<input defaultValue="$100,000"/></label><label>Maximum salary<input defaultValue="$160,000"/></label></div></section>
      <section className="panel"><span className="eyebrow">Work style</span><h2>Location & flexibility</h2><div className="choice-grid">{["Remote","Hybrid","On-site"].map(x=><label className="choice" key={x}><input type="checkbox" defaultChecked={x!=="On-site"}/><span>{x}</span></label>)}</div><div className="form-fields"><label>Preferred location<input defaultValue="United States"/></label><label>Experience level<select defaultValue="Mid Level"><option>Entry Level</option><option>Mid Level</option><option>Senior</option><option>Lead</option></select></label></div></section>
      <section className="panel wide-panel"><span className="eyebrow">Agent behavior</span><h2>Application preferences</h2>{["Customize resume for each job","Generate customized cover letter","Generate answers to application questions","Skip jobs outside salary range"].map((x,i)=><div className="toggle-row" key={x}><div><strong>{x}</strong><small>{i===0?"Tailor the presentation of your existing experience to the job.":"Let the agent prepare this information for your review."}</small></div><input type="checkbox" defaultChecked={i<3}/></div>)}<div className="approval-callout"><strong>Require approval before submission</strong><span>Recommended. The agent will stop and let you review every application before it is submitted.</span><input type="checkbox" defaultChecked/></div></section>
    </div>
  </>;
}