import { ArrowRight, Bot, CheckCircle2, FileText, Sparkles, Target } from "lucide-react";
import { Link } from "react-router-dom";

export default function Welcome() {
  return <div className="welcome-page">
    <nav className="welcome-nav"><div className="brand"><div className="brand-mark">J</div><div><strong>JobPilot</strong><span>AI Career Agent</span></div></div><Link to="/dashboard" className="secondary-btn">Open dashboard <ArrowRight size={15}/></Link></nav>
    <section className="hero"><div className="hero-copy"><span className="hero-pill"><Sparkles size={14}/> AI-powered job search</span><h1>Find jobs.<br/><em>Apply smarter.</em></h1><p>Upload your resume, define your preferences, and let your AI agent discover matching opportunities and prepare applications for your review.</p><div className="hero-actions"><Link to="/dashboard" className="primary-btn">Get Started <ArrowRight size={17}/></Link><Link to="/jobs" className="secondary-btn">Explore jobs</Link></div><div className="trust-row"><span><CheckCircle2 size={15}/> Resume-aware matching</span><span><CheckCircle2 size={15}/> Human approval</span></div></div>
    <div className="hero-visual"><div className="floating-card top"><div className="mini-icon"><Target size={17}/></div><div><strong>94% match</strong><span>Senior Golang Developer</span></div></div><div className="agent-window"><div className="window-head"><span className="window-dot"/><span className="window-dot"/><span className="window-dot"/><strong>JobPilot Agent</strong></div><div className="agent-window-body"><div className="agent-avatar"><Bot size={25}/></div><h3>AI Agent is working</h3><p>Analyzing jobs against your resume...</p><div className="progress"><span style={{width:"73%"}}/></div><div className="agent-steps"><span className="done">✓ Find matching jobs</span><span className="done">✓ Analyze requirements</span><span className="current">● Prepare application</span><span>○ Ask for approval</span></div></div></div><div className="floating-card bottom"><FileText size={18}/><div><strong>Application ready</strong><span>Review before submission</span></div></div></div></section>
    <section className="feature-section"><div><span className="eyebrow">Built for your workflow</span><h2>From resume to submitted application.</h2></div><div className="feature-grid"><div className="feature"><div className="feature-icon"><FileText/></div><h3>Resume Intelligence</h3><p>Keep your experience, skills and preferences structured for better job matching.</p></div><div className="feature"><div className="feature-icon"><Target/></div><h3>Smart Matching</h3><p>Surface opportunities based on your actual profile instead of generic keyword searches.</p></div><div className="feature"><div className="feature-icon"><Bot/></div><h3>AI Application Assistant</h3><p>Prepare application information and let you review it before submission.</p></div></div></section>
  </div>;
}